### ISSUE TITLE
specify the version of metamask and chrome

### ISSUE THREAD

**Issue by usstdqq** [Xeift/Metamask-Selenium-Auto-Import-Mnemonic#1]
hey, thanks for sharing the code first! may I ask what's the metamask and chrome/edge browser version you are using?

**Comment by Xeift** [comment]
10.28.3 Edge

**Comment by Xeift** [comment]
I'll update detailed information and upload both edge and chrome version code later.

**Comment by Xeift** [comment]
Done
I've updated some files, check out readme.md

**Comment by usstdqq** [comment]
thanks! closing this issue.

**Comment by usstdqq** [comment]
for completeness, I tested with the chome metamask 10.35.1 version with the file modification trick. the chome script works.
